"""Add User Metrics and Daily Challenges

Revision ID: 5cdb292c6cf5
Revises: a4e00b49641a
Create Date: 2026-03-08 23:43:36.138672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdb292c6cf5'
down_revision: Union[str, Sequence[str], None] = 'a4e00b49641a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
