"""Add UserDailyActivity, UserBadge, DailyChallenge, User metrics

Revision ID: a4e00b49641a
Revises: 5905a723d87a
Create Date: 2026-03-08 23:09:13.283611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e00b49641a'
down_revision: Union[str, Sequence[str], None] = '5905a723d87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('problem_type', sa.String(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_challenges_date'), 'daily_challenges', ['date'], unique=True)
    op.create_index(op.f('ix_daily_challenges_id'), 'daily_challenges', ['id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('badge_name', sa.String(), nullable=True),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_badges_id'), 'user_badges', ['id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('user_daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_daily_activity_date'), 'user_daily_activity', ['date'], unique=False)
    op.create_index(op.f('ix_user_daily_activity_id'), 'user_daily_activity', ['id'], unique=False)
    op.create_index(op.f('ix_user_daily_activity_user_id'), 'user_daily_activity', ['user_id'], unique=False)
    op.add_column('users', sa.Column('reputation', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'reputation')
    op.drop_index(op.f('ix_user_daily_activity_user_id'), table_name='user_daily_activity')
    op.drop_index(op.f('ix_user_daily_activity_id'), table_name='user_daily_activity')
    op.drop_index(op.f('ix_user_daily_activity_date'), table_name='user_daily_activity')
    op.drop_table('user_daily_activity')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_daily_challenges_id'), table_name='daily_challenges')
    op.drop_index(op.f('ix_daily_challenges_date'), table_name='daily_challenges')
    op.drop_table('daily_challenges')
    # ### end Alembic commands ###
